<?php require_once __DIR__ . '/header.phtml'; ?>

<h2>Iniciar sesión</h2>

<?php if (!empty($error)): ?>
    <p style="color:red"><?= $error ?></p>
<?php endif; ?>

<form action="<?= BASE_URL ?>verify" method="POST">
    <label>Usuario</label>
    <input type="text" name="username" required>

    <label>Contraseña</label>
    <input type="password" name="password" required>

    <button type="submit">Ingresar</button>
</form>

<?php require_once __DIR__ . '/footer.phtml'; ?>