<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sistema de Liga</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="<?= BASE_URL ?>assets/styles.css">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
        <a class="navbar-brand" href="<?= route_url('ligas') ?>"><i class="bi bi-trophy-fill"></i> Sistema Liga</a>
        <div class="navbar-nav">
            <a class="nav-link" href="<?= route_url('ligas') ?>">Ligas</a>
            <a class="nav-link" href="<?= route_url('equipos') ?>">Equipos</a>
                 <?php if (!isset($_SESSION['ID_USER'])): ?>
            <a class="nav-link" href="<?= route_url('login') ?>">Iniciar Sesión</a>
              <a class="nav-link" href="<?= route_url('register') ?>">Registrarse</a>
            <?php endif; ?>
              
            <?php
            if (isset($_SESSION['ID_USER'])): ?>
                <a class="nav-link" href="<?= route_url('logout') ?>">Cerrar Sesión</a>
            <?php endif; ?>
        </div>
    </div>
</nav>